# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sidebar.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1428, 736)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.widget_3 = QtWidgets.QWidget(self.centralwidget)
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.widget = QtWidgets.QWidget(self.widget_3)
        self.widget.setMinimumSize(QtCore.QSize(0, 40))
        self.widget.setStyleSheet("background-color: rgb(170, 170, 127);")
        self.widget.setObjectName("widget")
        self.change_btn = QtWidgets.QPushButton(self.widget)
        self.change_btn.setGeometry(QtCore.QRect(30, 10, 24, 20))
        self.change_btn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/icon/menu-4-32.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.change_btn.setIcon(icon)
        self.change_btn.setIconSize(QtCore.QSize(14, 14))
        self.change_btn.setCheckable(True)
        self.change_btn.setObjectName("change_btn")
        self.layoutWidget = QtWidgets.QWidget(self.widget)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 2, 2))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.logo_label_6 = QtWidgets.QLabel(self.widget)
        self.logo_label_6.setGeometry(QtCore.QRect(90, 0, 40, 40))
        self.logo_label_6.setMinimumSize(QtCore.QSize(40, 40))
        self.logo_label_6.setMaximumSize(QtCore.QSize(40, 40))
        self.logo_label_6.setText("")
        self.logo_label_6.setPixmap(QtGui.QPixmap(":/icon/icon/fast-food.png"))
        self.logo_label_6.setScaledContents(True)
        self.logo_label_6.setObjectName("logo_label_6")
        self.logo_label_7 = QtWidgets.QLabel(self.widget)
        self.logo_label_7.setGeometry(QtCore.QRect(260, 0, 541, 40))
        font = QtGui.QFont()
        font.setPointSize(35)
        font.setBold(True)
        font.setWeight(75)
        self.logo_label_7.setFont(font)
        self.logo_label_7.setObjectName("logo_label_7")
        self.logo_label_8 = QtWidgets.QLabel(self.widget)
        self.logo_label_8.setGeometry(QtCore.QRect(840, 0, 40, 40))
        self.logo_label_8.setMinimumSize(QtCore.QSize(40, 40))
        self.logo_label_8.setMaximumSize(QtCore.QSize(40, 40))
        self.logo_label_8.setText("")
        self.logo_label_8.setPixmap(QtGui.QPixmap(":/icon/icon/fast-food.png"))
        self.logo_label_8.setScaledContents(True)
        self.logo_label_8.setObjectName("logo_label_8")
        self.verticalLayout_5.addWidget(self.widget)
        self.stackedWidget = QtWidgets.QStackedWidget(self.widget_3)
        self.stackedWidget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.page)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.page_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.page_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.page_4)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.widget_2 = QtWidgets.QWidget(self.page_4)
        self.widget_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.widget_2.setObjectName("widget_2")
        self.home_btn_6 = QtWidgets.QPushButton(self.widget_2)
        self.home_btn_6.setGeometry(QtCore.QRect(30, 0, 161, 201))
        self.home_btn_6.setToolTipDuration(2)
        self.home_btn_6.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icon/icon/White Minimalist Modern UI Welcome News Widget Notification Instagram Story.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.home_btn_6.setIcon(icon1)
        self.home_btn_6.setIconSize(QtCore.QSize(300, 250))
        self.home_btn_6.setCheckable(True)
        self.home_btn_6.setAutoExclusive(True)
        self.home_btn_6.setObjectName("home_btn_6")
        self.home_btn_7 = QtWidgets.QPushButton(self.widget_2)
        self.home_btn_7.setGeometry(QtCore.QRect(180, 0, 161, 201))
        self.home_btn_7.setToolTipDuration(2)
        self.home_btn_7.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icon/icon/White Minimalist Modern UI Welcome News Widget Notification Instagram Story (1).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.home_btn_7.setIcon(icon2)
        self.home_btn_7.setIconSize(QtCore.QSize(300, 250))
        self.home_btn_7.setCheckable(True)
        self.home_btn_7.setAutoExclusive(True)
        self.home_btn_7.setObjectName("home_btn_7")
        self.home_btn_8 = QtWidgets.QPushButton(self.widget_2)
        self.home_btn_8.setGeometry(QtCore.QRect(330, 0, 161, 201))
        self.home_btn_8.setToolTipDuration(2)
        self.home_btn_8.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icon/icon/White Minimalist Modern UI Welcome News Widget Notification Instagram Story (5).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.home_btn_8.setIcon(icon3)
        self.home_btn_8.setIconSize(QtCore.QSize(300, 250))
        self.home_btn_8.setCheckable(True)
        self.home_btn_8.setAutoExclusive(True)
        self.home_btn_8.setObjectName("home_btn_8")
        self.home_btn_9 = QtWidgets.QPushButton(self.widget_2)
        self.home_btn_9.setGeometry(QtCore.QRect(480, 0, 161, 201))
        self.home_btn_9.setToolTipDuration(2)
        self.home_btn_9.setText("")
        icon_bihun = QtGui.QIcon()
        icon_bihun.addPixmap(QtGui.QPixmap(":/icon/icon/White Minimalist Modern UI Welcome News Widget Notification Instagram Story (8).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.home_btn_9.setIcon(icon_bihun)
        self.home_btn_9.setIconSize(QtCore.QSize(300, 250))
        self.home_btn_9.setCheckable(True)
        self.home_btn_9.setAutoExclusive(True)
        self.home_btn_9.setObjectName("home_btn_9")
        self.home_btn_10 = QtWidgets.QPushButton(self.widget_2)
        self.home_btn_10.setGeometry(QtCore.QRect(620, 0, 201, 201))
        self.home_btn_10.setToolTipDuration(2)
        self.home_btn_10.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icon/icon/White Minimalist Modern UI Welcome News Widget Notification Instagram Story (9).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.home_btn_10.setIcon(icon4)
        self.home_btn_10.setIconSize(QtCore.QSize(300, 250))
        self.home_btn_10.setCheckable(True)
        self.home_btn_10.setAutoExclusive(True)
        self.home_btn_10.setObjectName("home_btn_10")
        self.home_btn_11 = QtWidgets.QPushButton(self.widget_2)
        self.home_btn_11.setGeometry(QtCore.QRect(30, 240, 161, 201))
        self.home_btn_11.setToolTipDuration(2)
        self.home_btn_11.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icon/icon/White Minimalist Modern UI Welcome News Widget Notification Instagram Story (4).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.home_btn_11.setIcon(icon5)
        self.home_btn_11.setIconSize(QtCore.QSize(300, 250))
        self.home_btn_11.setCheckable(True)
        self.home_btn_11.setAutoExclusive(True)
        self.home_btn_11.setObjectName("home_btn_11")
        self.home_btn_12 = QtWidgets.QPushButton(self.widget_2)
        self.home_btn_12.setGeometry(QtCore.QRect(180, 240, 161, 201))
        self.home_btn_12.setToolTipDuration(2)
        self.home_btn_12.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icon/icon/White Minimalist Modern UI Welcome News Widget Notification Instagram Story (6).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.home_btn_12.setIcon(icon6)
        self.home_btn_12.setIconSize(QtCore.QSize(300, 250))
        self.home_btn_12.setCheckable(True)
        self.home_btn_12.setAutoExclusive(True)
        self.home_btn_12.setObjectName("home_btn_12")
        self.home_btn_13 = QtWidgets.QPushButton(self.widget_2)
        self.home_btn_13.setGeometry(QtCore.QRect(330, 240, 161, 201))
        self.home_btn_13.setToolTipDuration(2)
        self.home_btn_13.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icon/icon/White Minimalist Modern UI Welcome News Widget Notification Instagram Story (3).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.home_btn_13.setIcon(icon7)
        self.home_btn_13.setIconSize(QtCore.QSize(300, 250))
        self.home_btn_13.setCheckable(True)
        self.home_btn_13.setAutoExclusive(True)
        self.home_btn_13.setObjectName("home_btn_13")
        self.home_btn_14 = QtWidgets.QPushButton(self.widget_2)
        self.home_btn_14.setGeometry(QtCore.QRect(480, 240, 161, 201))
        self.home_btn_14.setToolTipDuration(2)
        self.home_btn_14.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icon/icon/White Minimalist Modern UI Welcome News Widget Notification Instagram Story (10).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.home_btn_14.setIcon(icon8)
        self.home_btn_14.setIconSize(QtCore.QSize(300, 250))
        self.home_btn_14.setCheckable(True)
        self.home_btn_14.setAutoExclusive(True)
        self.home_btn_14.setObjectName("home_btn_14")
        self.home_btn_15 = QtWidgets.QPushButton(self.widget_2)
        self.home_btn_15.setGeometry(QtCore.QRect(630, 240, 161, 201))
        self.home_btn_15.setToolTipDuration(2)
        self.home_btn_15.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icon/icon/White Minimalist Modern UI Welcome News Widget Notification Instagram Story (2).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.home_btn_15.setIcon(icon9)
        self.home_btn_15.setIconSize(QtCore.QSize(300, 250))
        self.home_btn_15.setCheckable(True)
        self.home_btn_15.setAutoExclusive(True)
        self.home_btn_15.setObjectName("home_btn_15")
        self.home_btn_16 = QtWidgets.QPushButton(self.widget_2)
        self.home_btn_16.setGeometry(QtCore.QRect(780, 0, 171, 201))
        self.home_btn_16.setToolTipDuration(2)
        self.home_btn_16.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/icon/icon/White Minimalist Modern UI Welcome News Widget Notification Instagram Story (7).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.home_btn_16.setIcon(icon10)
        self.home_btn_16.setIconSize(QtCore.QSize(300, 250))
        self.home_btn_16.setCheckable(True)
        self.home_btn_16.setAutoExclusive(True)
        self.home_btn_16.setObjectName("home_btn_16")
        self.home_btn_17 = QtWidgets.QPushButton(self.widget_2)
        self.home_btn_17.setGeometry(QtCore.QRect(790, 240, 141, 201))
        self.home_btn_17.setToolTipDuration(2)
        self.home_btn_17.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/icon/icon/makanan.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.home_btn_17.setIcon(icon11)
        self.home_btn_17.setIconSize(QtCore.QSize(175, 250))
        self.home_btn_17.setCheckable(True)
        self.home_btn_17.setAutoExclusive(True)
        self.home_btn_17.setObjectName("home_btn_17")
        self.widget_4 = QtWidgets.QWidget(self.widget_2)
        self.widget_4.setGeometry(QtCore.QRect(0, 520, 911, 291))
        self.widget_4.setObjectName("widget_4")
        self.label = QtWidgets.QLabel(self.widget_2)
        self.label.setGeometry(QtCore.QRect(280, 10, 431, 451))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/icon/icon/White Minimalist Modern UI Welcome News Widget Notification Instagram Story (11).png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.customers_btn_3 = QtWidgets.QPushButton(self.widget_2)
        self.customers_btn_3.setGeometry(QtCore.QRect(320, 30, 31, 31))
        self.customers_btn_3.setText("")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/icon/icon/account-logout-64.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.customers_btn_3.setIcon(icon12)
        self.customers_btn_3.setIconSize(QtCore.QSize(20, 20))
        self.customers_btn_3.setCheckable(True)
        self.customers_btn_3.setAutoExclusive(True)
        self.customers_btn_3.setObjectName("customers_btn_3")
        self.label_2 = QtWidgets.QLabel(self.widget_2)
        self.label_2.setGeometry(QtCore.QRect(280, 10, 431, 441))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/icon/icon/White Minimalist Modern UI Welcome News Widget Notification Instagram Story (21).png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.widget_2)
        self.label_3.setGeometry(QtCore.QRect(280, 10, 431, 451))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap(":/icon/icon/White Minimalist Modern UI Welcome News Widget Notification Instagram Story (16).png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.widget_2)
        self.label_4.setGeometry(QtCore.QRect(280, 10, 431, 441))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap(":/icon/icon/White Minimalist Modern UI Welcome News Widget Notification Instagram Story (13).png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.widget_2)
        self.label_5.setGeometry(QtCore.QRect(280, 10, 431, 441))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap(":/icon/icon/White Minimalist Modern UI Welcome News Widget Notification Instagram Story (20).png"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.widget_2)
        self.label_6.setGeometry(QtCore.QRect(280, 10, 431, 431))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap(":/icon/icon/White Minimalist Modern UI Welcome News Widget Notification Instagram Story (12).png"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.widget_2)
        self.label_7.setGeometry(QtCore.QRect(280, 10, 431, 451))
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap(":/icon/icon/White Minimalist Modern UI Welcome News Widget Notification Instagram Story (14).png"))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        self.label_9 = QtWidgets.QLabel(self.widget_2)
        self.label_9.setGeometry(QtCore.QRect(280, 10, 431, 451))
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap(":/icon/icon/White Minimalist Modern UI Welcome News Widget Notification Instagram Story (17).png"))
        self.label_9.setScaledContents(True)
        self.label_9.setObjectName("label_9")
        self.label_11 = QtWidgets.QLabel(self.widget_2)
        self.label_11.setGeometry(QtCore.QRect(280, 10, 431, 451))
        self.label_11.setText("")
        self.label_11.setPixmap(QtGui.QPixmap(":/icon/icon/White Minimalist Modern UI Welcome News Widget Notification Instagram Story (15).png"))
        self.label_11.setScaledContents(True)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.widget_2)
        self.label_12.setGeometry(QtCore.QRect(290, 10, 421, 441))
        self.label_12.setText("")
        self.label_12.setPixmap(QtGui.QPixmap(":/icon/icon/White Minimalist Modern UI Welcome News Widget Notification Instagram Story (18).png"))
        self.label_12.setScaledContents(True)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.widget_2)
        self.label_13.setGeometry(QtCore.QRect(280, 10, 421, 441))
        self.label_13.setText("")
        self.label_13.setPixmap(QtGui.QPixmap(":/icon/icon/White Minimalist Modern UI Welcome News Widget Notification Instagram Story (19).png"))
        self.label_13.setScaledContents(True)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.widget_2)
        self.label_14.setGeometry(QtCore.QRect(280, 10, 431, 451))
        self.label_14.setText("")
        self.label_14.setPixmap(QtGui.QPixmap(":/icon/icon/resep.jpg"))
        self.label_14.setScaledContents(True)
        self.label_14.setObjectName("label_14")
        self.pushButton_3 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_3.setGeometry(QtCore.QRect(0, 20, 161, 171))
        self.pushButton_3.setText("")
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/nutri/icon/nutrisi_page-0002.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon13)
        self.pushButton_3.setIconSize(QtCore.QSize(130, 280))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_4.setGeometry(QtCore.QRect(160, 20, 181, 181))
        self.pushButton_4.setText("")
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/nutri/icon/nutrisi_page-0001.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon14)
        self.pushButton_4.setIconSize(QtCore.QSize(130, 280))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_5.setGeometry(QtCore.QRect(330, 20, 181, 181))
        self.pushButton_5.setText("")
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(":/nutri/icon/nutrisi_page-0003.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_5.setIcon(icon15)
        self.pushButton_5.setIconSize(QtCore.QSize(130, 280))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_7 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_7.setGeometry(QtCore.QRect(660, 20, 181, 191))
        self.pushButton_7.setText("")
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(":/nutri/icon/nutrisi_page-0005.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_7.setIcon(icon16)
        self.pushButton_7.setIconSize(QtCore.QSize(130, 280))
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_8.setGeometry(QtCore.QRect(840, 20, 181, 181))
        self.pushButton_8.setText("")
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(":/nutri/icon/nutrisi_page-0006.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_8.setIcon(icon17)
        self.pushButton_8.setIconSize(QtCore.QSize(130, 280))
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_9.setGeometry(QtCore.QRect(-10, 240, 181, 181))
        self.pushButton_9.setText("")
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap(":/nutri/icon/nutrisi_page-0007.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_9.setIcon(icon18)
        self.pushButton_9.setIconSize(QtCore.QSize(130, 280))
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_10.setGeometry(QtCore.QRect(160, 240, 181, 181))
        self.pushButton_10.setText("")
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap(":/nutri/icon/nutrisi_page-0012.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_10.setIcon(icon19)
        self.pushButton_10.setIconSize(QtCore.QSize(130, 280))
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_11 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_11.setGeometry(QtCore.QRect(330, 240, 181, 181))
        self.pushButton_11.setText("")
        icon20 = QtGui.QIcon()
        icon20.addPixmap(QtGui.QPixmap(":/nutri/icon/nutrisi_page-0009.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_11.setIcon(icon20)
        self.pushButton_11.setIconSize(QtCore.QSize(130, 280))
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_12 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_12.setGeometry(QtCore.QRect(500, 240, 181, 181))
        self.pushButton_12.setText("")
        icon21 = QtGui.QIcon()
        icon21.addPixmap(QtGui.QPixmap(":/nutri/icon/nutrisi_page-0010.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_12.setIcon(icon21)
        self.pushButton_12.setIconSize(QtCore.QSize(130, 280))
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_13 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_13.setGeometry(QtCore.QRect(680, 240, 181, 181))
        self.pushButton_13.setText("")
        icon22 = QtGui.QIcon()
        icon22.addPixmap(QtGui.QPixmap(":/nutri/icon/nutrisi_page-0011.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_13.setIcon(icon22)
        self.pushButton_13.setIconSize(QtCore.QSize(130, 280))
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_14 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_14.setGeometry(QtCore.QRect(850, 250, 181, 171))
        self.pushButton_14.setText("")
        icon23 = QtGui.QIcon()
        icon23.addPixmap(QtGui.QPixmap(":/nutri/icon/nutrisi_page-0013.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_14.setIcon(icon23)
        self.pushButton_14.setIconSize(QtCore.QSize(130, 280))
        self.pushButton_14.setObjectName("pushButton_14")
        self.widget_5 = QtWidgets.QWidget(self.widget_2)
        self.widget_5.setGeometry(QtCore.QRect(-10, 180, 1521, 61))
        self.widget_5.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.widget_5.setObjectName("widget_5")
        self.widget_6 = QtWidgets.QWidget(self.widget_2)
        self.widget_6.setGeometry(QtCore.QRect(0, 410, 1041, 61))
        self.widget_6.setObjectName("widget_6")
        self.widget_7 = QtWidgets.QWidget(self.widget_2)
        self.widget_7.setGeometry(QtCore.QRect(0, 0, 1051, 21))
        self.widget_7.setObjectName("widget_7")
        self.pushButton_6 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_6.setGeometry(QtCore.QRect(500, 0, 181, 211))
        self.pushButton_6.setText("")
        icon24 = QtGui.QIcon()
        icon24.addPixmap(QtGui.QPixmap(":/nutri/icon/nutrisi_page-0004.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_6.setIcon(icon24)
        self.pushButton_6.setIconSize(QtCore.QSize(130, 280))
        self.pushButton_6.setObjectName("pushButton_6")
        self.home_btn_10.raise_()
        self.home_btn_6.raise_()
        self.home_btn_7.raise_()
        self.home_btn_8.raise_()
        self.home_btn_9.raise_()
        self.home_btn_11.raise_()
        self.home_btn_12.raise_()
        self.home_btn_13.raise_()
        self.home_btn_14.raise_()
        self.home_btn_15.raise_()
        self.home_btn_16.raise_()
        self.home_btn_17.raise_()
        self.widget_4.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.label_7.raise_()
        self.label_9.raise_()
        self.label_11.raise_()
        self.label_12.raise_()
        self.label_13.raise_()
        self.label_14.raise_()
        self.customers_btn_3.raise_()
        self.pushButton_3.raise_()
        self.pushButton_4.raise_()
        self.pushButton_7.raise_()
        self.pushButton_8.raise_()
        self.pushButton_9.raise_()
        self.pushButton_10.raise_()
        self.pushButton_11.raise_()
        self.pushButton_12.raise_()
        self.pushButton_13.raise_()
        self.pushButton_14.raise_()
        self.pushButton_5.raise_()
        self.widget_6.raise_()
        self.pushButton_6.raise_()
        self.widget_7.raise_()
        self.widget_5.raise_()
        self.gridLayout_5.addWidget(self.widget_2, 0, 1, 1, 1)
        self.stackedWidget.addWidget(self.page_4)
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.page_5)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_8 = QtWidgets.QLabel(self.page_5)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_8.setFont(font)
        self.label_8.setText("")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout_6.addWidget(self.label_8, 1, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_5)
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setObjectName("page_6")
        self.pushButton = QtWidgets.QPushButton(self.page_6)
        self.pushButton.setGeometry(QtCore.QRect(70, 10, 71, 101))
        self.pushButton.setStyleSheet("border-radius: 25px;\n"
"padding-left:20px;\n"
"")
        self.pushButton.setText("")
        self.pushButton.setCheckable(True)
        self.pushButton.setAutoExclusive(True)
        self.pushButton.setObjectName("pushButton")
        self.stackedWidget.addWidget(self.page_6)
        self.page_7 = QtWidgets.QWidget()
        self.page_7.setObjectName("page_7")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.page_7)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_10 = QtWidgets.QLabel(self.page_7)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_10.setFont(font)
        self.label_10.setText("")
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout_8.addWidget(self.label_10, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_7)
        self.verticalLayout_5.addWidget(self.stackedWidget)
        self.gridLayout.addWidget(self.widget_3, 0, 1, 1, 1)
        self.full_menu_widget = QtWidgets.QWidget(self.centralwidget)
        self.full_menu_widget.setStyleSheet("QWidget{\n"
"background-color: rgb(255, 213, 105);\n"
"}\n"
"\n"
"QPushButton{\n"
"    color:white;\n"
"    text-align:left;\n"
"    height : 30px;\n"
"    border: none;\n"
"    padding-left: 10px;\n"
"}\n"
"\n"
"")
        self.full_menu_widget.setObjectName("full_menu_widget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.full_menu_widget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.logo_label_2 = QtWidgets.QLabel(self.full_menu_widget)
        self.logo_label_2.setMinimumSize(QtCore.QSize(40, 40))
        self.logo_label_2.setMaximumSize(QtCore.QSize(40, 40))
        self.logo_label_2.setText("")
        self.logo_label_2.setPixmap(QtGui.QPixmap(":/icon/icon/fast-food.png"))
        self.logo_label_2.setScaledContents(True)
        self.logo_label_2.setObjectName("logo_label_2")
        self.horizontalLayout_2.addWidget(self.logo_label_2)
        self.logo_label_3 = QtWidgets.QLabel(self.full_menu_widget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.logo_label_3.setFont(font)
        self.logo_label_3.setScaledContents(True)
        self.logo_label_3.setObjectName("logo_label_3")
        self.horizontalLayout_2.addWidget(self.logo_label_3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.home_btn_2 = QtWidgets.QPushButton(self.full_menu_widget)
        icon25 = QtGui.QIcon()
        icon25.addPixmap(QtGui.QPixmap(":/icon/icon/home-4-32.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon25.addPixmap(QtGui.QPixmap(":/icon/icon/home-4-48.ico"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.home_btn_2.setIcon(icon25)
        self.home_btn_2.setIconSize(QtCore.QSize(14, 14))
        self.home_btn_2.setCheckable(True)
        self.home_btn_2.setAutoExclusive(True)
        self.home_btn_2.setObjectName("home_btn_2")
        self.verticalLayout_2.addWidget(self.home_btn_2)
        self.customers_btn_2 = QtWidgets.QPushButton(self.full_menu_widget)
        icon26 = QtGui.QIcon()
        icon26.addPixmap(QtGui.QPixmap(":/icon/icon/dashboard-5-32.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon26.addPixmap(QtGui.QPixmap(":/icon/icon/dashboard-5-48.ico"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.customers_btn_2.setIcon(icon26)
        self.customers_btn_2.setIconSize(QtCore.QSize(14, 14))
        self.customers_btn_2.setCheckable(True)
        self.customers_btn_2.setAutoExclusive(True)
        self.customers_btn_2.setObjectName("customers_btn_2")
        self.verticalLayout_2.addWidget(self.customers_btn_2)
        self.verticalLayout_4.addLayout(self.verticalLayout_2)
        spacerItem = QtWidgets.QSpacerItem(20, 373, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.exit_btn_2 = QtWidgets.QPushButton(self.full_menu_widget)
        icon27 = QtGui.QIcon()
        icon27.addPixmap(QtGui.QPixmap(":/icon/icon/close-window-64.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.exit_btn_2.setIcon(icon27)
        self.exit_btn_2.setIconSize(QtCore.QSize(14, 14))
        self.exit_btn_2.setObjectName("exit_btn_2")
        self.verticalLayout_4.addWidget(self.exit_btn_2)
        self.gridLayout.addWidget(self.full_menu_widget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(3)
        self.exit_btn_2.clicked.connect(MainWindow.close) # type: ignore
        self.change_btn.toggled['bool'].connect(self.full_menu_widget.setHidden) # type: ignore
        self.home_btn_14.toggled['bool'].connect(self.label.setVisible) # type: ignore
        self.customers_btn_3.toggled['bool'].connect(self.label.setHidden) # type: ignore
        self.home_btn_14.toggled['bool'].connect(self.customers_btn_3.setVisible) # type: ignore
        self.home_btn_6.toggled['bool'].connect(self.label_2.setVisible) # type: ignore
        self.customers_btn_3.toggled['bool'].connect(self.label_2.setHidden) # type: ignore
        self.home_btn_6.toggled['bool'].connect(self.customers_btn_3.setVisible) # type: ignore
        self.home_btn_6.toggled['bool'].connect(self.label.setHidden) # type: ignore
        self.home_btn_7.toggled['bool'].connect(self.label.setHidden) # type: ignore
        self.home_btn_8.toggled['bool'].connect(self.label.setHidden) # type: ignore
        self.home_btn_9.toggled['bool'].connect(self.label.setHidden) # type: ignore
        self.home_btn_10.toggled['bool'].connect(self.label.setHidden) # type: ignore
        self.home_btn_15.toggled['bool'].connect(self.label.setHidden) # type: ignore
        self.home_btn_16.toggled['bool'].connect(self.label.setHidden) # type: ignore
        self.home_btn_17.toggled['bool'].connect(self.label.setHidden) # type: ignore
        self.home_btn_15.toggled['bool'].connect(self.label.setHidden) # type: ignore
        self.home_btn_12.toggled['bool'].connect(self.label.setHidden) # type: ignore
        self.home_btn_11.toggled['bool'].connect(self.label.setHidden) # type: ignore
        self.home_btn_13.toggled['bool'].connect(self.label.setHidden) # type: ignore
        self.home_btn_15.toggled['bool'].connect(self.label_2.setHidden) # type: ignore
        self.home_btn_17.toggled['bool'].connect(self.label_2.setHidden) # type: ignore
        self.home_btn_14.toggled['bool'].connect(self.label_2.setHidden) # type: ignore
        self.home_btn_13.toggled['bool'].connect(self.label_2.setHidden) # type: ignore
        self.home_btn_12.toggled['bool'].connect(self.label_2.setHidden) # type: ignore
        self.home_btn_11.toggled['bool'].connect(self.label_2.setHidden) # type: ignore
        self.home_btn_7.toggled['bool'].connect(self.label_2.setHidden) # type: ignore
        self.home_btn_8.toggled['bool'].connect(self.label_2.setHidden) # type: ignore
        self.home_btn_9.toggled['bool'].connect(self.label_2.setHidden) # type: ignore
        self.home_btn_10.toggled['bool'].connect(self.label_2.setHidden) # type: ignore
        self.home_btn_16.toggled['bool'].connect(self.label_2.setHidden) # type: ignore
        self.home_btn_6.toggled['bool'].connect(self.label_3.setHidden) # type: ignore
        self.home_btn_7.toggled['bool'].connect(self.label_3.setHidden) # type: ignore
        self.home_btn_8.toggled['bool'].connect(self.label_3.setVisible) # type: ignore
        self.home_btn_9.toggled['bool'].connect(self.label_3.setHidden) # type: ignore
        self.home_btn_10.toggled['bool'].connect(self.label_3.setHidden) # type: ignore
        self.home_btn_16.toggled['bool'].connect(self.label_3.setHidden) # type: ignore
        self.home_btn_17.toggled['bool'].connect(self.label_3.setHidden) # type: ignore
        self.home_btn_15.toggled['bool'].connect(self.label_3.setHidden) # type: ignore
        self.home_btn_14.toggled['bool'].connect(self.label_3.setHidden) # type: ignore
        self.home_btn_13.toggled['bool'].connect(self.label_3.setHidden) # type: ignore
        self.home_btn_12.toggled['bool'].connect(self.label_3.setHidden) # type: ignore
        self.home_btn_11.toggled['bool'].connect(self.label_3.setHidden) # type: ignore
        self.customers_btn_3.toggled['bool'].connect(self.label_3.setHidden) # type: ignore
        self.home_btn_8.toggled['bool'].connect(self.customers_btn_3.setVisible) # type: ignore
        self.home_btn_6.toggled['bool'].connect(self.label_4.setHidden) # type: ignore
        self.home_btn_7.toggled['bool'].connect(self.label_4.setHidden) # type: ignore
        self.home_btn_8.toggled['bool'].connect(self.label_4.setHidden) # type: ignore
        self.home_btn_9.toggled['bool'].connect(self.label_4.setVisible) # type: ignore
        self.home_btn_10.toggled['bool'].connect(self.label_4.setHidden) # type: ignore
        self.home_btn_16.toggled['bool'].connect(self.label_4.setHidden) # type: ignore
        self.home_btn_17.toggled['bool'].connect(self.label_4.setHidden) # type: ignore
        self.home_btn_15.toggled['bool'].connect(self.label_4.setHidden) # type: ignore
        self.home_btn_14.toggled['bool'].connect(self.label_4.setHidden) # type: ignore
        self.home_btn_13.toggled['bool'].connect(self.label_4.setHidden) # type: ignore
        self.home_btn_11.toggled['bool'].connect(self.label_4.setHidden) # type: ignore
        self.customers_btn_3.toggled['bool'].connect(self.label_4.setHidden) # type: ignore
        self.home_btn_9.toggled['bool'].connect(self.customers_btn_3.setVisible) # type: ignore
        self.home_btn_12.toggled['bool'].connect(self.label_4.setHidden) # type: ignore
        self.home_btn_7.toggled['bool'].connect(self.label_5.setVisible) # type: ignore
        self.home_btn_6.toggled['bool'].connect(self.label_5.setHidden) # type: ignore
        self.home_btn_12.toggled['bool'].connect(self.label_5.setHidden) # type: ignore
        self.home_btn_11.toggled['bool'].connect(self.label_5.setHidden) # type: ignore
        self.home_btn_15.toggled['bool'].connect(self.label_5.setHidden) # type: ignore
        self.home_btn_17.toggled['bool'].connect(self.label_5.setHidden) # type: ignore
        self.home_btn_16.toggled['bool'].connect(self.label_5.setHidden) # type: ignore
        self.home_btn_10.toggled['bool'].connect(self.label_5.setHidden) # type: ignore
        self.home_btn_10.toggled['bool'].connect(self.label_5.setHidden) # type: ignore
        self.home_btn_9.toggled['bool'].connect(self.label_5.setHidden) # type: ignore
        self.home_btn_8.toggled['bool'].connect(self.label_5.setVisible) # type: ignore
        self.home_btn_7.toggled['bool'].connect(self.customers_btn_3.setVisible) # type: ignore
        self.customers_btn_3.toggled['bool'].connect(self.label_5.setHidden) # type: ignore
        self.home_btn_8.toggled['bool'].connect(self.label_5.setHidden) # type: ignore
        self.home_btn_13.toggled['bool'].connect(self.label_5.setHidden) # type: ignore
        self.home_btn_14.toggled['bool'].connect(self.label_5.setHidden) # type: ignore
        self.home_btn_10.toggled['bool'].connect(self.label_6.setVisible) # type: ignore
        self.home_btn_9.toggled['bool'].connect(self.label_6.setHidden) # type: ignore
        self.home_btn_8.toggled['bool'].connect(self.label_6.setHidden) # type: ignore
        self.home_btn_17.toggled['bool'].connect(self.label_6.setHidden) # type: ignore
        self.home_btn_16.toggled['bool'].connect(self.label_6.setHidden) # type: ignore
        self.home_btn_7.toggled['bool'].connect(self.label_6.setHidden) # type: ignore
        self.home_btn_14.toggled['bool'].connect(self.label_6.setHidden) # type: ignore
        self.home_btn_6.toggled['bool'].connect(self.label_6.setHidden) # type: ignore
        self.home_btn_12.toggled['bool'].connect(self.label_6.setHidden) # type: ignore
        self.home_btn_13.toggled['bool'].connect(self.label_6.setHidden) # type: ignore
        self.home_btn_11.toggled['bool'].connect(self.label_6.setHidden) # type: ignore
        self.customers_btn_3.toggled['bool'].connect(self.label_6.setHidden) # type: ignore
        self.home_btn_10.toggled['bool'].connect(self.customers_btn_3.setVisible) # type: ignore
        self.home_btn_15.toggled['bool'].connect(self.label_6.setHidden) # type: ignore
        self.home_btn_6.toggled['bool'].connect(self.label_7.setHidden) # type: ignore
        self.home_btn_7.toggled['bool'].connect(self.label_7.setHidden) # type: ignore
        self.home_btn_8.toggled['bool'].connect(self.label_7.setHidden) # type: ignore
        self.home_btn_9.toggled['bool'].connect(self.label_7.setHidden) # type: ignore
        self.home_btn_10.toggled['bool'].connect(self.label_7.setHidden) # type: ignore
        self.home_btn_16.toggled['bool'].connect(self.label_7.setVisible) # type: ignore
        self.home_btn_16.toggled['bool'].connect(self.label_7.setVisible) # type: ignore
        self.home_btn_17.toggled['bool'].connect(self.label_7.setHidden) # type: ignore
        self.home_btn_15.toggled['bool'].connect(self.label_7.setHidden) # type: ignore
        self.home_btn_14.toggled['bool'].connect(self.label_7.setHidden) # type: ignore
        self.home_btn_13.toggled['bool'].connect(self.label_7.setHidden) # type: ignore
        self.home_btn_12.toggled['bool'].connect(self.label_7.setHidden) # type: ignore
        self.home_btn_11.toggled['bool'].connect(self.label_7.setHidden) # type: ignore
        self.customers_btn_3.toggled['bool'].connect(self.label_7.setHidden) # type: ignore
        self.home_btn_16.toggled['bool'].connect(self.customers_btn_3.setVisible) # type: ignore
        self.home_btn_6.toggled['bool'].connect(self.label_9.setHidden) # type: ignore
        self.home_btn_6.toggled['bool'].connect(self.label_9.setHidden) # type: ignore
        self.home_btn_7.toggled['bool'].connect(self.label_9.setHidden) # type: ignore
        self.home_btn_8.toggled['bool'].connect(self.label_9.setHidden) # type: ignore
        self.home_btn_9.toggled['bool'].connect(self.label_9.setHidden) # type: ignore
        self.home_btn_10.toggled['bool'].connect(self.label_9.setHidden) # type: ignore
        self.home_btn_16.toggled['bool'].connect(self.label_9.setHidden) # type: ignore
        self.home_btn_17.toggled['bool'].connect(self.label_9.setHidden) # type: ignore
        self.home_btn_15.toggled['bool'].connect(self.label_9.setHidden) # type: ignore
        self.home_btn_14.toggled['bool'].connect(self.label_9.setHidden) # type: ignore
        self.home_btn_13.toggled['bool'].connect(self.label_9.setHidden) # type: ignore
        self.home_btn_12.toggled['bool'].connect(self.label_9.setHidden) # type: ignore
        self.home_btn_11.toggled['bool'].connect(self.label_9.setVisible) # type: ignore
        self.customers_btn_3.toggled['bool'].connect(self.label_9.setHidden) # type: ignore
        self.home_btn_11.toggled['bool'].connect(self.customers_btn_3.setVisible) # type: ignore
        self.home_btn_12.toggled['bool'].connect(self.label_11.setVisible) # type: ignore
        self.home_btn_11.toggled['bool'].connect(self.label_11.setHidden) # type: ignore
        self.home_btn_6.toggled['bool'].connect(self.label_11.setHidden) # type: ignore
        self.home_btn_7.toggled['bool'].connect(self.label_11.setHidden) # type: ignore
        self.home_btn_8.toggled['bool'].connect(self.label_11.setHidden) # type: ignore
        self.home_btn_9.toggled['bool'].connect(self.label_11.setHidden) # type: ignore
        self.home_btn_14.toggled['bool'].connect(self.label_11.setHidden) # type: ignore
        self.home_btn_15.toggled['bool'].connect(self.label_11.setHidden) # type: ignore
        self.home_btn_17.toggled['bool'].connect(self.label_11.setHidden) # type: ignore
        self.home_btn_16.toggled['bool'].connect(self.label_11.setHidden) # type: ignore
        self.home_btn_10.toggled['bool'].connect(self.label_11.setHidden) # type: ignore
        self.customers_btn_3.toggled['bool'].connect(self.label_11.setHidden) # type: ignore
        self.home_btn_12.toggled['bool'].connect(self.customers_btn_3.setVisible) # type: ignore
        self.home_btn_13.toggled['bool'].connect(self.label_11.setHidden) # type: ignore
        self.home_btn_6.toggled['bool'].connect(self.label_12.setHidden) # type: ignore
        self.home_btn_7.toggled['bool'].connect(self.label_12.setHidden) # type: ignore
        self.home_btn_8.toggled['bool'].connect(self.label_12.setHidden) # type: ignore
        self.home_btn_9.toggled['bool'].connect(self.label_12.setHidden) # type: ignore
        self.home_btn_10.toggled['bool'].connect(self.label_12.setHidden) # type: ignore
        self.home_btn_16.toggled['bool'].connect(self.label_12.setHidden) # type: ignore
        self.home_btn_17.toggled['bool'].connect(self.label_12.setHidden) # type: ignore
        self.home_btn_15.toggled['bool'].connect(self.label_12.setHidden) # type: ignore
        self.home_btn_14.toggled['bool'].connect(self.label_12.setHidden) # type: ignore
        self.home_btn_13.toggled['bool'].connect(self.label_12.setVisible) # type: ignore
        self.home_btn_12.toggled['bool'].connect(self.label_12.setHidden) # type: ignore
        self.home_btn_11.toggled['bool'].connect(self.label_12.setHidden) # type: ignore
        self.customers_btn_3.toggled['bool'].connect(self.label_12.setHidden) # type: ignore
        self.home_btn_13.toggled['bool'].connect(self.customers_btn_3.setVisible) # type: ignore
        self.home_btn_6.toggled['bool'].connect(self.label_13.setHidden) # type: ignore
        self.home_btn_11.toggled['bool'].connect(self.label_13.setHidden) # type: ignore
        self.home_btn_7.toggled['bool'].connect(self.label_13.setHidden) # type: ignore
        self.home_btn_8.toggled['bool'].connect(self.label_13.setHidden) # type: ignore
        self.home_btn_9.toggled['bool'].connect(self.label_13.setHidden) # type: ignore
        self.home_btn_10.toggled['bool'].connect(self.label_13.setHidden) # type: ignore
        self.home_btn_16.toggled['bool'].connect(self.label_13.setHidden) # type: ignore
        self.home_btn_17.toggled['bool'].connect(self.label_13.setHidden) # type: ignore
        self.home_btn_15.toggled['bool'].connect(self.label_13.setHidden) # type: ignore
        self.home_btn_14.toggled['bool'].connect(self.label_13.setHidden) # type: ignore
        self.home_btn_13.toggled['bool'].connect(self.label_13.setHidden) # type: ignore
        self.home_btn_12.toggled['bool'].connect(self.label_13.setHidden) # type: ignore
        self.home_btn_11.toggled['bool'].connect(self.label_13.setHidden) # type: ignore
        self.home_btn_11.toggled['bool'].connect(self.label_13.setHidden) # type: ignore
        self.customers_btn_3.toggled['bool'].connect(self.label_13.setHidden) # type: ignore
        self.home_btn_15.toggled['bool'].connect(self.customers_btn_3.setVisible) # type: ignore
        self.home_btn_15.toggled['bool'].connect(self.label_13.setVisible) # type: ignore
        self.home_btn_17.toggled['bool'].connect(self.label_14.setVisible) # type: ignore
        self.home_btn_16.toggled['bool'].connect(self.label_14.setHidden) # type: ignore
        self.home_btn_15.toggled['bool'].connect(self.label_14.setHidden) # type: ignore
        self.home_btn_10.toggled['bool'].connect(self.label_14.setHidden) # type: ignore
        self.home_btn_9.toggled['bool'].connect(self.label_14.setHidden) # type: ignore
        self.home_btn_14.toggled['bool'].connect(self.label_14.setHidden) # type: ignore
        self.home_btn_8.toggled['bool'].connect(self.label_14.setHidden) # type: ignore
        self.home_btn_13.toggled['bool'].connect(self.label_14.setHidden) # type: ignore
        self.home_btn_12.toggled['bool'].connect(self.label_14.setHidden) # type: ignore
        self.home_btn_7.toggled['bool'].connect(self.label_14.setHidden) # type: ignore
        self.home_btn_6.toggled['bool'].connect(self.label_14.setHidden) # type: ignore
        self.home_btn_6.toggled['bool'].connect(self.label_14.setHidden) # type: ignore
        self.home_btn_11.toggled['bool'].connect(self.label_14.setHidden) # type: ignore
        self.customers_btn_3.toggled['bool'].connect(self.label_14.setHidden) # type: ignore
        self.home_btn_17.toggled['bool'].connect(self.customers_btn_3.setVisible) # type: ignore
        self.home_btn_2.toggled['bool'].connect(self.label_7.setHidden) # type: ignore
        self.customers_btn_2.toggled['bool'].connect(self.label_9.setHidden) # type: ignore
        self.home_btn_2.toggled['bool'].connect(self.label_9.setHidden) # type: ignore
        self.customers_btn_2.toggled['bool'].connect(self.customers_btn_3.setHidden) # type: ignore
        self.home_btn_2.toggled['bool'].connect(self.label_13.setHidden) # type: ignore
        self.customers_btn_2.toggled['bool'].connect(self.label_13.setHidden) # type: ignore
        self.customers_btn_2.toggled['bool'].connect(self.label_14.setHidden) # type: ignore
        self.customers_btn_2.toggled['bool'].connect(self.label_11.setHidden) # type: ignore
        self.home_btn_2.toggled['bool'].connect(self.label_11.setHidden) # type: ignore
        self.home_btn_2.toggled['bool'].connect(self.label_4.setHidden) # type: ignore
        self.customers_btn_2.toggled['bool'].connect(self.label.setHidden) # type: ignore
        self.customers_btn_2.toggled['bool'].connect(self.home_btn_15.setHidden) # type: ignore
        self.customers_btn_2.toggled['bool'].connect(self.home_btn_17.setHidden) # type: ignore
        self.customers_btn_2.toggled['bool'].connect(self.home_btn_8.setHidden) # type: ignore
        self.home_btn_2.toggled['bool'].connect(self.label_12.setHidden) # type: ignore
        self.customers_btn_2.toggled['bool'].connect(self.home_btn_11.setHidden) # type: ignore
        self.customers_btn_2.toggled['bool'].connect(self.home_btn_12.setHidden) # type: ignore
        self.home_btn_2.toggled['bool'].connect(self.label_14.setHidden) # type: ignore
        self.customers_btn_2.toggled['bool'].connect(self.home_btn_13.setHidden) # type: ignore
        self.customers_btn_2.toggled['bool'].connect(self.home_btn_7.setHidden) # type: ignore
        self.customers_btn_2.toggled['bool'].connect(self.home_btn_16.setHidden) # type: ignore
        self.home_btn_2.toggled['bool'].connect(self.label_3.setHidden) # type: ignore
        self.customers_btn_2.toggled['bool'].connect(self.label_3.setHidden) # type: ignore
        self.customers_btn_2.toggled['bool'].connect(self.label_12.setHidden) # type: ignore
        self.customers_btn_2.toggled['bool'].connect(self.home_btn_6.setHidden) # type: ignore
        self.customers_btn_2.toggled['bool'].connect(self.customers_btn_3.setVisible) # type: ignore
        self.home_btn_2.toggled['bool'].connect(self.customers_btn_3.setHidden) # type: ignore
        self.home_btn_2.toggled['bool'].connect(self.label_2.setHidden) # type: ignore
        self.customers_btn_2.toggled['bool'].connect(self.label_5.setHidden) # type: ignore
        self.home_btn_2.toggled['bool'].connect(self.label_5.setHidden) # type: ignore
        self.customers_btn_2.toggled['bool'].connect(self.label_4.setHidden) # type: ignore
        self.customers_btn_2.toggled['bool'].connect(self.label_6.setHidden) # type: ignore
        self.customers_btn_2.toggled['bool'].connect(self.label_6.setHidden) # type: ignore
        self.home_btn_2.toggled['bool'].connect(self.label_6.setHidden) # type: ignore
        self.customers_btn_2.toggled['bool'].connect(self.home_btn_14.setHidden) # type: ignore
        self.customers_btn_2.toggled['bool'].connect(self.home_btn_9.setHidden) # type: ignore
        self.home_btn_2.toggled['bool'].connect(self.label.setHidden) # type: ignore
        self.customers_btn_2.toggled['bool'].connect(self.home_btn_16.setHidden) # type: ignore
        self.customers_btn_2.toggled['bool'].connect(self.label_2.setHidden) # type: ignore
        self.customers_btn_2.toggled['bool'].connect(self.home_btn_10.setHidden) # type: ignore
        self.customers_btn_2.toggled['bool'].connect(self.label_7.setHidden) # type: ignore
        self.customers_btn_2.toggled['bool'].connect(self.customers_btn_3.setHidden) # type: ignore
        self.home_btn_2.toggled['bool'].connect(self.pushButton_4.setHidden) # type: ignore
        self.home_btn_2.toggled['bool'].connect(self.pushButton_9.setHidden) # type: ignore
        self.home_btn_2.toggled['bool'].connect(self.pushButton_9.setHidden) # type: ignore
        self.home_btn_2.toggled['bool'].connect(self.pushButton_10.setHidden) # type: ignore
        self.home_btn_2.toggled['bool'].connect(self.pushButton_11.setHidden) # type: ignore
        self.home_btn_2.toggled['bool'].connect(self.pushButton_12.setHidden) # type: ignore
        self.home_btn_2.toggled['bool'].connect(self.pushButton_12.setHidden) # type: ignore
        self.home_btn_2.toggled['bool'].connect(self.pushButton_13.setHidden) # type: ignore
        self.home_btn_2.toggled['bool'].connect(self.pushButton_14.setHidden) # type: ignore
        self.home_btn_2.toggled['bool'].connect(self.pushButton_6.setHidden) # type: ignore
        self.home_btn_2.toggled['bool'].connect(self.pushButton_6.setHidden) # type: ignore
        self.home_btn_2.toggled['bool'].connect(self.pushButton_5.setHidden) # type: ignore
        self.home_btn_2.toggled['bool'].connect(self.pushButton_7.setHidden) # type: ignore
        self.home_btn_2.toggled['bool'].connect(self.pushButton_3.setHidden) # type: ignore
        self.home_btn_2.toggled['bool'].connect(self.pushButton_8.setHidden) # type: ignore
        self.home_btn_2.toggled['bool'].connect(self.widget_5.setHidden) # type: ignore
        self.home_btn_2.toggled['bool'].connect(self.widget_6.setHidden) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.logo_label_7.setText(_translate("MainWindow", "Selamat Datang Di Ngilers"))
        self.logo_label_3.setText(_translate("MainWindow", "ngilers"))
        self.home_btn_2.setText(_translate("MainWindow", "Dashboard"))
        self.customers_btn_2.setText(_translate("MainWindow", "Nutrition"))
        self.exit_btn_2.setText(_translate("MainWindow", "Exit"))
import resource_rc
